ai:
    store:
        qdrant:
            ctbg-criteria:
                endpoint: '%env(QDRANT_DSN)%'
                api_key: '%env(QDRANT_API_KEY)%'
                collection_name: 'ctbg-criteria'
                dimensions: 768

            ctbg-resolutions:
                endpoint: '%env(QDRANT_DSN)%'
                api_key: '%env(QDRANT_API_KEY)%'
                collection_name: 'ctbg-resolutions'
                dimensions: 768
