flysystem:
    storages:
        default.storage:
            adapter: 'aws'
            options:
                client: 'aws_s3_client'
                bucket: '%env(AWS_S3_BUCKET_NAME)%'
                prefix: 'default'
        documents.storage:
            adapter: 'aws'
            options:
                client: 'aws_s3_client'
                bucket: '%env(AWS_S3_BUCKET_NAME)%'
                prefix: 'documents'
        resolutions.storage:
            adapter: 'aws'
            options:
                client: 'aws_s3_client'
                bucket: '%env(AWS_S3_BUCKET_NAME)%'
                prefix: 'resolutions'
        criteria.storage:
            adapter: 'aws'
            options:
                client: 'aws_s3_client'
                bucket: '%env(AWS_S3_BUCKET_NAME)%'
                prefix: 'criteria'
        judgments.storage:
            adapter: 'aws'
            options:
                client: 'aws_s3_client'
                bucket: '%env(AWS_S3_BUCKET_NAME)%'
                prefix: 'judgments'

