# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'

    #esi: true
    #fragments: true

when@prod:
    framework:
        trusted_proxies: '%env(TRUSTED_PROXIES)%'
        trusted_headers: ['x-forwarded-for', 'x-forwarded-proto', 'x-forwarded-host', 'x-forwarded-port']
        session:
            handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
            save_path: '%env(REDIS_URL)%'
            cookie_secure: true
            cookie_samesite: lax

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
