LOAD DATABASE
  FROM ${MYSQL_URL}
  INTO ${POSTGRES_URL}

WITH include no drop, create no tables, create no indexes,
     disable triggers, reset sequences

ALTER SCHEMA 'db' RENAME TO 'public'

EXCLUDING TABLE NAMES MATCHING 'doctrine_migration_versions', 'messenger_messages', 'resolution'

CAST type binary when (= 16 precision) to uuid drop typemod using byte-vector-to-hexstring
;
