<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Creates the `ai_chat_messages` table for per-user, per-thread chat history
 * storage (Issue #91 — agentic drafting flow, Fase 5).
 *
 * Design:
 *  - One row per (user_id, thread_id) pair.
 *  - `turns` stores the full history as a JSONB array of {role, kind, content, ts} objects.
 *  - `user_id` is a mandatory isolation column — every read/write filters by it.
 *
 * Thread ID convention (generated by ChatHistoryStore::threadId()):
 *   request:{uuid}                  ← access-request draft chat
 *   complaint:{uuid}:{mode}         ← complaint/alegation draft chat
 *
 * The old history in AccessRequest::metadata is kept as a read fallback
 * for existing sessions and migrated lazily on the first write.
 *
 * Fully idempotent: CREATE TABLE IF NOT EXISTS + ADD CONSTRAINT IF NOT EXISTS.
 */
final class Version20260621120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create ai_chat_messages table for per-user agentic chat history (Issue #91).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE IF NOT EXISTS ai_chat_messages (
                id          BIGSERIAL PRIMARY KEY,
                user_id     UUID        NOT NULL,
                thread_id   VARCHAR(200) NOT NULL,
                turns       JSONB       NOT NULL DEFAULT '[]',
                updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CONSTRAINT fk_ai_chat_messages_user
                    FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE
            )
        SQL);

        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_chat_messages_thread
                ON ai_chat_messages (user_id, thread_id)
        SQL);

        $this->addSql(<<<'SQL'
            CREATE INDEX IF NOT EXISTS idx_ai_chat_messages_user
                ON ai_chat_messages (user_id)
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS ai_chat_messages');
    }
}
