<?php

declare(strict_types=1);

namespace App\Service\Consult;

use App\Entity\AccessRequest;
use App\Entity\Document;
use App\Entity\User;
use App\Enum\DocumentType;
use Doctrine\ORM\EntityManagerInterface;
use League\Flysystem\FilesystemOperator;

/**
 * Persists a document generated by the free-consultation chat (`flow=consult`)
 * into the request's dossier as an INERT typed Document: it shows up in the docs
 * list but NEVER runs {@see \App\Service\Document\DocumentEffectsApplier} — no
 * state transition, no timeline entry, no complaint auto-creation. The recipe
 * mirrors {@see \App\Service\Complaint\ComplaintGenerator::saveComplaint} (HTML
 * blob in the documents storage + a typed Document row) minus the single-draft
 * reuse and the effect wiring. Used for every consult type EXCEPT the ones that
 * integrate into a dedicated pipeline (Complaint / AlegationResponse).
 */
final class ConsultDocumentPersister
{
    public function __construct(
        private readonly FilesystemOperator $documentsStorage,
        private readonly EntityManagerInterface $entityManager,
    ) {
    }

    /**
     * @param array<string, mixed> $meta merged into aiMetadata
     */
    public function persist(AccessRequest $ar, DocumentType $type, string $html, string $title, User $user, array $meta = []): Document
    {
        $filename = sprintf(
            'consult_%s_%s.html',
            $ar->getId()->toRfc4122(),
            (new \DateTime())->format('Y-m-d_H-i-s')
        );
        $this->documentsStorage->write($filename, $html);

        $document = new Document();
        $document->setOriginalFilename(($title !== '' ? $title : 'Documento') . '.html');
        if ($title !== '') {
            $document->setCustomName($title);
        }
        $document->setMimeType('text/html');
        $document->setType($type);
        $document->setAccessRequest($ar);
        $document->setUploadedBy($user);
        $document->setProcessed(true);
        $document->setStoredFilename($filename);
        $document->setFileSize(strlen($html));
        $document->setContentHash(hash('sha256', $html));
        $document->setAiMetadata(array_merge([
            'origin' => 'consult',
            'title' => $title,
            'generatedAt' => (new \DateTime())->format('c'),
        ], $meta));

        $this->entityManager->persist($document);
        $this->entityManager->flush();

        return $document;
    }
}
